//--------------------A---------------------------//
when record level access is applied then the user can only get the view of records rather than updating or inserting anything. while in the Field level access it gives the user permission to execute DML operations

//-------------------------B-----------------------------//
I would design like withsharing it gives the the data access.

public class with sharing....

//--------------------C----------------------//
CRUD is create, retrive,update,delete. when data is not available create not available needs the record the retrive and when needs to change anything of the available data use update and when not required use delete.

//-----------------D-----------------//
